"""GitHub integration via the `gh` CLI: create an issue from a finding or
open a fix PR (branch + commit) - Aikido-style 'real fix' actions.

All commands run inside the scanned repository so gh picks up its remote.
"""
import json
import re
import subprocess
from pathlib import Path

BRANCH_PREFIX = "gatekeeper-fix"


class GhError(RuntimeError):
    pass


def _run(cmd, cwd, timeout=120):
    try:
        proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True,
                              timeout=timeout)
    except FileNotFoundError:
        raise GhError("gh CLI not found (brew install gh)")
    except subprocess.TimeoutExpired:
        raise GhError(f"gh timed out after {timeout}s")
    if proc.returncode != 0:
        msg = (proc.stderr or proc.stdout or "").strip().splitlines()
        raise GhError(msg[-1][:200] if msg else f"gh exited {proc.returncode}")
    return proc.stdout


def gh_available(target) -> bool:
    try:
        subprocess.run(["gh", "--version"], capture_output=True, timeout=15)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False
    return Path(target, ".git").exists()


def repo_slug(target) -> str:
    out = _run(["gh", "repo", "view", "--json", "nameWithOwner", "-q",
                ".nameWithOwner"], cwd=str(target))
    return out.strip()


def _finding_body(f: dict, target: str) -> str:
    lines = [
        f"**Severity:** {f.get('severity', '?')}  |  **Risk score:** {f.get('risk_score', '?')}/100",
        f"**Tool:** {f.get('tool', '?')} ({f.get('category', '?')})",
        f"**Location:** `{f.get('file', 'n/a')}"
        + (f":{f.get('line')}" if f.get('line') else "") + "`",
    ]
    if f.get("cvss") is not None:
        lines.append(f"**CVSS:** {f['cvss']}")
    if f.get("cwe"):
        owasp = f" | **OWASP:** {f['owasp']}" if f.get("owasp") else ""
        lines.append(f"**CWE:** {f['cwe']}{owasp}")
    if f.get("package"):
        lines.append(f"**Package:** `{f['package']}`")
    if f.get("introduced_via"):
        lines.append(f"**Introduced via:** {' → '.join(f['introduced_via'])}")
    lines += ["", "## What", f.get("description", "n/a"),
              "", "## How to fix", f.get("remediation_hint", "n/a")]
    if f.get("code_snippet"):
        lines += ["", "## Current code", "```", f["code_snippet"], "```"]
    lines += ["", f"_Generated by Gatekeeper for `{target}`_"]
    return "\n".join(lines)


def _labels(f: dict) -> list:
    labels = [f"severity:{(f.get('severity') or 'info').lower()}",
              f"type:{f.get('category', 'sast')}"]
    return labels


def create_issue(target, finding: dict) -> dict:
    title = f"[Gatekeeper] [{finding.get('severity', '?')}] {finding.get('title', 'issue')}"[:220]
    body = _finding_body(finding, str(target))
    cmd = ["gh", "issue", "create", "--title", title, "--body", body]
    for label in _labels(finding):
        cmd += ["--label", label]
    out = _run(cmd, cwd=str(target))
    url = out.strip().splitlines()[-1]
    return {"url": url}


def _sanitized_slug(f: dict) -> str:
    base = f"{f.get('category', 'issue')}-{f.get('file', '')}-{f.get('line', 0)}"
    slug = re.sub(r"[^a-zA-Z0-9._-]+", "-", base).strip("-").lower()[:60]
    return slug or "issue"


def create_fix_pr(target, finding: dict, fix_prompt: str, commit_message: str = None) -> dict:
    """Create a branch, apply nothing itself - it commits an instruction file
    and lets the caller (agent) commit code. Simpler contract: this creates
    branch + empty-ish commit marker and a draft PR with the fix directives,
    so an AI agent or human can push the real fix to that branch."""
    target = Path(target)
    slug = _sanitized_slug(finding)
    branch = f"{BRANCH_PREFIX}/{slug}"

    _run(["git", "checkout", "-b", branch], cwd=str(target))
    marker = target / ".gatekeeper-fix-prompt.md"
    marker.write_text(fix_prompt)
    _run(["git", "add", marker.name], cwd=str(target))
    msg = commit_message or f"gatekeeper: fix plan for {finding.get('title', 'issue')}"[:100]
    _run(["git", "commit", "-m", msg], cwd=str(target))
    _run(["git", "push", "-u", "origin", branch], cwd=str(target))
    title = f"[Gatekeeper] Fix: {finding.get('title', 'security issue')}"[:200]
    body = _finding_body(finding, str(target)) + (
        "\n\n## Fix directives\n\n" + fix_prompt)
    out = _run(["gh", "pr", "create", "--title", title, "--body", body,
                "--draft"], cwd=str(target))
    url = out.strip().splitlines()[-1]
    _run(["git", "checkout", "-"], cwd=str(target))
    return {"url": url, "branch": branch}
